version: '3.8'

services:
  db:
    build: .
    image: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Database7894
      POSTGRES_DB: escola

  ecole_database:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ecole_database:/var/lib/postgresql/data

  ecole_api:
    depends_on:
      - ecole_database
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"

volumes:
  ecole_database:
